name: Python CI/CD

on:
push:

branches:

- main

env:
PYTEST REPORT PATH: pytest_report. html
CODE_PATH: src/Task4.py

jobs:
test:
  runs-on: ubuntu-latest

steps:
- name: Checkout code
  uses: actions/checkout@v3

name: Install Python
uses: actions/setup-pythonev4
with:
    python-version: '3.8'
    architecture: 'x64'

name: Install project dependencies
run: pip install -r requirements. txt

name: Run tests
run: pytest --html=${{ env.PYTEST REPORT PATH }} --self-contained-html


name: Upload artifact
uses: actions/upload-artifact@v3
  if: ${{!cancelled()}}
  with:
    name: test-results
    path: ${{ env.PYTEST REPORT PATH }}

upload artifact:
needs: tests
runs-on: ubuntu-latest

SEDs:
- name: Checkout code
  uses: actions/checkout@v3

- name: Upload artifact
  uses: actions/upload-artifact@v3
  with:
    name: code
  path: ${{ env.CODE PATH }}
